/*ERROR: LINEA 8 | COLUMNA 1 | NO PUEDE VENIR NADA DESPUÉS DEL MÉTODO MAIN! Se esperaba: EOF, se encontró: class*/
class Prueba {

}
fn main () {

}
class Error {

}